#pragma once

#include "Basement.hpp"
#include "BouncingBalls.hpp"
#include "Bowling.hpp"
#include "CamelCase.hpp"
#include "CoinSums.hpp"
#include "CutVector.hpp"
#include "DiceGame.hpp"
#include "GCD.hpp"
#include "Median.hpp"
#include "Smallest.hpp"
#include "SmallOrLarge.hpp"
#include "SnowDay.hpp"
#include "SumOfSquares.hpp"
#include "FizzBuzz.hpp"
#include "ForLoopIndex.hpp"